### ISSUE TITLE
Change arrangement / organization on the YCHANGE platform

### ISSUE THREAD

**Issue by tammets** [YCHANGE-PROJECT/YCHANGE#17]
Organise sample project on YCHANGE project platform according to the following levels:

**Level A.) Language:**
As folder: English – Deutsch – Français – Italiano – Čeština – Eesti

**Level B.) Topics:**
as folders (title with max. three words): e.g. Lignite Mining Germany, Flooding in Switzerland

**Level C.) Sample Project files:**
Teacher information and sample project instructions (2 – 3 files)

**Comment by tammets** [comment]
We'll need topics here. We can use categories at the moment.

**Comment by pjotrsavitski** [comment]
This one would cover "Student project" elements, not "Sample project" ones.

**Comment by pjotrsavitski** [comment]
Changes require some more testing before marking the issue as closed.

**Comment by pjotrsavitski** [comment]
Seems to be working well enough. Closing the issue.

The listings are the same as in the rest of the system and follow the same pagination logic (including the limits).
