### ISSUE TITLE
Add bullet points under “How to participate”

### ISSUE THREAD

**Issue by tammets** [YCHANGE-PROJECT/YCHANGE#24]
on main page:
- ~~“Register as a new user and create a group
to start a project (How to?)” = **link to tutorials**~~
- ~~“Sign up for your country group to receive the latest information” = **link to groups**~~

<img width="1094" alt="screen shot 2018-01-09 at 14 08 42" src="https://user-images.githubusercontent.com/380007/34720273-c5d31112-f546-11e7-9936-a85916481501.png">

**Comment by pjotrsavitski** [comment]
Added textual content to the platform, changed it a bit to comply with the rest of the texts.
