### ISSUE TITLE
Add country emails on bottom part of main page

### ISSUE THREAD

**Issue by tammets** [YCHANGE-PROJECT/YCHANGE#25]

**Comment by pjotrsavitski** [comment]
Need a list of country emails.

**Comment by pjotrsavitski** [comment]
We could use these:

* germany@ychange.eu
* switzerland@ychange.eu
* czech-republic@ychange.eu
* estonia@ychange.eu

A different texts could be used, but that would prevent from the copy-paste method. Although, clicking on an element would work well enough. Using special letters in email addresses might not be a good idea, so we tried to stick to the alphanumerical one (pretty much).
