### ISSUE TITLE
Add new link to new static page "Video tutorials"

### ISSUE THREAD

**Issue by tammets** [YCHANGE-PROJECT/YCHANGE#3]
Page will be used for linking video tutorials.

<img width="1045" alt="screen shot 2017-05-23 at 16 12 34" src="https://cloud.githubusercontent.com/assets/380007/26355838/cb58c67e-3fd2-11e7-953c-f1f9ab52ccee.png">

**Comment by pjotrsavitski** [comment]
Should it only allow linking of video tutorials or embedding those?

If we are to need embedding, then this has to be allowed. Any active elements are being purged from the input by default.
