### ISSUE TITLE
Include language options (“please choose your language”: English – Deutsch – Francais – Italiano-Eesti) as an option when registering to set page language

### ISSUE THREAD

**Issue by tammets** [YCHANGE-PROJECT/YCHANGE#31]
![screen shot 2018-01-09 at 12 56 40](https://user-images.githubusercontent.com/380007/34717707-9eaf06a4-f53c-11e7-9c27-3fe1c28da509.png)

**Comment by pjotrsavitski** [comment]
Also added Czech to the list of languages.
