### ISSUE TITLE
Create landing page (under “pages”) on project platform with links to questionnaires (in different languages)

### ISSUE THREAD

**Issue by tammets** [YCHANGE-PROJECT/YCHANGE#35]
![screen shot 2018-01-08 at 14 21 04](https://user-images.githubusercontent.com/380007/34670502-4126ee24-f47f-11e7-9f44-e8091e3aa0df.png)

**Comment by pjotrsavitski** [comment]
Created a page under the management group: https://ychange.eu/pages/view/260/questionnaires
