### ISSUE TITLE
Extend section "Project samples": Download additionally via file symbol

### ISSUE THREAD

**Issue by MartinPetitMarteau** [YCHANGE-PROJECT/YCHANGE#40]
So far, downloading exemplary teaching material (e.g., PDFs) can be done only via the "Download" button in the upper right.
It may be helpful and more intuitive to additinally trigger the download via a click on the file symbol (red circle in the screenshot):
![ychangedownloadviafilesymbol](https://user-images.githubusercontent.com/16595636/34931296-5e7bb3b6-f9ce-11e7-9807-8ca82569918b.PNG)

**Comment by pjotrsavitski** [comment]
This could be done by either overriding a view on the backend side or extending a view with addition of JS that would make sure that Icon would become a link, copying the one from the Download button.

The latter one could be a bit less intrusive, but at the same time more of hack (elgg_extend_view with a value of less than 500 would prepend to the view).
