### ISSUE TITLE
Create own section "Curriculum"

### ISSUE THREAD

**Issue by MartinPetitMarteau** [YCHANGE-PROJECT/YCHANGE#43]
Provide an own section for the curriculum, for example after "Tutorials":
![unbenannt](https://user-images.githubusercontent.com/16595636/35439761-800f3774-029c-11e8-8162-551996db986e.PNG)

Provide content of English curriculum on this page, and also links to the curriculum PDFs in national languages.

Refrerences #26

**Comment by pjotrsavitski** [comment]
The content of this page could be translated into different languages (the ones within the defined set). In this case, only the main box should be filled with content and the others left empty, this would give the desired result.
